theme: jekyll-theme-slate
title: soilphysics
description: Basic and model-based soil physical analyses
url: https://arsilva87.github.io/soilphysics/
author: Da Silva & De Lima
plugins:
  - jekyll-seo-tag
google_analytics: UA-147928758-3
